### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by Chihab-E** [Adel-Qusay/ADEL-WAF#2]
I tried to start an sql injection and it didn't work 
Also this is the one on bac site

**Comment by Adel-Qusay** [comment]
Where did you test it, on bac site? 
Can you send screenshot of your inject attempt.

**Comment by Chihab-E** [comment]
![image](https://user-images.githubusercontent.com/66165473/236953632-20d0fbc0-b80d-449c-8857-e5cb4d4ebbb4.png)
Guess this is a good work also i try sql injection just for fun and not to do any harm to websites i don't start the attack i just test how vulnerable is the website

**Comment by Adel-Qusay** [comment]
Thank you very much, you seem like a talented young man
Please only do not test penetration in the official sites because the law will punish you
I hope you will develop your talent as a white hat hacker
good luck ;)

**Comment by Chihab-E** [comment]
Thank you very much for the beautiful words 
I hope i can succeed on my bac this year ♥️

**Comment by Chihab-E** [comment]
Hey it's me again, Can i contact u ?

**Comment by Adel-Qusay** [comment]
> Hey it's me again, Can i contact u ?

مرحبا، ابعثلي ايميل
